### ISSUE TITLE
VM Create/Edit/Delete

### ISSUE THREAD

**Issue by emresaracoglu** [aheahe/pve-cli-utils#1]
Hello,

Can I create/edir/delete a virtual machine with your application?
Thank you

**Comment by aheahe** [comment]
No. I have only needed and implementet storage related functionality, eg move to another storage, change disks to RAW etc. 

You can do it with the Proxmox API. But too create a machine with the CLI would mean a lot of options to specify (memory, disk, where to place the disk, sizes etc etc).
